'use strict';

var fs = require('fs');
var path = require('path');

// Parse AGENTS.md back into intermediate rule representation
// Looks for ## Global Rules / ## Conditional Rules sections
// Under those, ### headings become individual rules
// "Applies to: `glob`" lines restore glob patterns

function discover(dir) {
  var filePath = path.join(dir, 'AGENTS.md');
  if (!fs.existsSync(filePath)) return null;

  var content;
  try {
    content = fs.readFileSync(filePath, 'utf8');
  } catch (e) {
    return null;
  }

  if (!content || !content.trim()) return null;

  var rules = [];
  var lines = content.split('\n');
  var inGlobal = false;
  var inConditional = false;
  var currentRule = null;
  var bodyLines = [];

  function flushRule() {
    if (currentRule) {
      currentRule.body = bodyLines.join('\n').trim();
      if (currentRule.body) {
        rules.push(currentRule);
      }
      currentRule = null;
      bodyLines = [];
    }
  }

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];

    // Detect section headers
    if (/^## Global Rules/i.test(line)) {
      flushRule();
      inGlobal = true;
      inConditional = false;
      continue;
    }
    if (/^## Conditional Rules/i.test(line)) {
      flushRule();
      inGlobal = false;
      inConditional = true;
      continue;
    }

    // Skip top-level headers and generation comments
    if (/^# /.test(line)) continue;
    if (/^> Generated by/.test(line)) continue;

    // Rule heading (### level)
    var h3Match = line.match(/^### (.+)/);
    if (h3Match) {
      flushRule();
      var name = h3Match[1].trim();
      currentRule = {
        name: slugify(name),
        fileName: slugify(name) + '.mdc',
        description: name,
        globs: '',
        alwaysApply: inGlobal,
        body: '',
        hasFrontmatter: true
      };
      continue;
    }

    // If we hit a ## that isn't Global/Conditional, treat as a new section
    if (/^## /.test(line) && !inGlobal && !inConditional) {
      flushRule();
      var h2Match = line.match(/^## (.+)/);
      if (h2Match) {
        var h2Name = h2Match[1].trim();
        currentRule = {
          name: slugify(h2Name),
          fileName: slugify(h2Name) + '.mdc',
          description: h2Name,
          globs: '',
          alwaysApply: true,
          body: '',
          hasFrontmatter: true
        };
      }
      continue;
    }

    if (!currentRule) continue;

    // Extract glob from "Applies to: `pattern`" or "Originally scoped to: `pattern`"
    var globMatch = line.match(/^\*(?:Applies to|Originally scoped to): `([^`]+)`\*$/);
    if (globMatch) {
      currentRule.globs = globMatch[1];
      continue;
    }

    bodyLines.push(line);
  }

  flushRule();

  if (rules.length === 0) return null;

  return { rules: rules, skipped: [] };
}

function slugify(str) {
  return str.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}

module.exports = { discover: discover };
