'use strict';

var fs = require('fs');
var path = require('path');

// Parse CLAUDE.md back into intermediate rule representation
// Splits on ## headings. Sections under "File-Specific Rules" become conditional.
// "Originally scoped to: `glob`" lines restore glob patterns.

function discover(dir) {
  var filePath = path.join(dir, 'CLAUDE.md');
  if (!fs.existsSync(filePath)) return null;

  var content;
  try {
    content = fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '').replace(/\r\n/g, '\n');
  } catch (e) {
    return null;
  }

  if (!content || !content.trim()) return null;

  var rules = [];
  var lines = content.split('\n');
  var inFileSpecific = false;
  var currentRule = null;
  var bodyLines = [];

  function flushRule() {
    if (currentRule) {
      currentRule.body = bodyLines.join('\n').trim();
      if (currentRule.body) {
        rules.push(currentRule);
      }
      currentRule = null;
      bodyLines = [];
    }
  }

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];

    // Skip top-level heading and generation line
    if (/^# CLAUDE\.md/i.test(line)) continue;
    if (/^> Generated by/.test(line)) continue;
    if (/^> Note: CLAUDE\.md does not support/.test(line)) continue;

    // Detect file-specific section
    if (/^## File-Specific Rules/i.test(line)) {
      flushRule();
      inFileSpecific = true;
      continue;
    }

    // Horizontal rule as separator
    if (/^---$/.test(line) && !inFileSpecific) {
      continue;
    }

    // ## heading = new rule section
    var h2Match = line.match(/^## (.+)/);
    if (h2Match) {
      flushRule();
      var name = h2Match[1].trim();
      currentRule = {
        name: slugify(name),
        fileName: slugify(name) + '.mdc',
        description: name,
        globs: '',
        alwaysApply: !inFileSpecific,
        body: '',
        hasFrontmatter: true
      };
      continue;
    }

    // ### heading under file-specific = conditional rule
    var h3Match = line.match(/^### (.+)/);
    if (h3Match && inFileSpecific) {
      flushRule();
      var cName = h3Match[1].trim();
      currentRule = {
        name: slugify(cName),
        fileName: slugify(cName) + '.mdc',
        description: cName,
        globs: '',
        alwaysApply: false,
        body: '',
        hasFrontmatter: true
      };
      continue;
    }

    if (!currentRule) continue;

    // Extract glob
    var globMatch = line.match(/^\*Originally scoped to: `([^`]+)`\*$/);
    if (globMatch) {
      currentRule.globs = globMatch[1];
      continue;
    }

    bodyLines.push(line);
  }

  flushRule();

  if (rules.length === 0) return null;

  return { rules: rules, skipped: [] };
}

function slugify(str) {
  return str.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}

module.exports = { discover: discover };
