'use strict';

var fs = require('fs');
var path = require('path');

// Parse .github/copilot-instructions.md back into intermediate rule representation
// Splits on ## headings. "Originally scoped to: `glob`" restores conditional rules.

function discover(dir) {
  var filePath = path.join(dir, '.github', 'copilot-instructions.md');
  if (!fs.existsSync(filePath)) return null;

  var content;
  try {
    content = fs.readFileSync(filePath, 'utf8');
  } catch (e) {
    return null;
  }

  if (!content || !content.trim()) return null;

  var rules = [];
  var lines = content.split('\n');
  var currentRule = null;
  var bodyLines = [];

  function flushRule() {
    if (currentRule) {
      currentRule.body = bodyLines.join('\n').trim();
      if (currentRule.body) {
        rules.push(currentRule);
      }
      currentRule = null;
      bodyLines = [];
    }
  }

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];

    // Skip top-level heading and generation line
    if (/^# Copilot Instructions/i.test(line)) continue;
    if (/^> Generated by/.test(line)) continue;

    // ## heading = new rule
    var h2Match = line.match(/^## (.+)/);
    if (h2Match) {
      flushRule();
      var name = h2Match[1].trim();
      currentRule = {
        name: slugify(name),
        fileName: slugify(name) + '.mdc',
        description: name,
        globs: '',
        alwaysApply: true,
        body: '',
        hasFrontmatter: true
      };
      continue;
    }

    if (!currentRule) continue;

    // Extract glob — if found, mark as conditional
    var globMatch = line.match(/^\*Originally scoped to: `([^`]+)`\*$/);
    if (globMatch) {
      currentRule.globs = globMatch[1];
      currentRule.alwaysApply = false;
      continue;
    }

    bodyLines.push(line);
  }

  flushRule();

  if (rules.length === 0) {
    // Treat entire file as one global rule
    return {
      rules: [{
        name: 'copilot-instructions',
        fileName: 'copilot-instructions.mdc',
        description: 'Copilot Instructions',
        globs: '',
        alwaysApply: true,
        body: content.trim(),
        hasFrontmatter: false
      }],
      skipped: []
    };
  }

  return { rules: rules, skipped: [] };
}

function slugify(str) {
  return str.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}

module.exports = { discover: discover };
