'use strict';

// Convert parsed Cursor rules to AGENTS.md format
// Structure:
//   # AGENTS.md
//   ## Global Rules (alwaysApply rules)
//   ## Rules for [pattern] (conditional rules)

function convert(rules) {
  var lines = [];
  var warnings = [];

  var globalRules = rules.filter(function(r) { return r.alwaysApply; });
  var conditionalRules = rules.filter(function(r) { return !r.alwaysApply; });

  lines.push('# AGENTS.md');
  lines.push('');
  lines.push('> Generated by [rule-porter](https://github.com/nedcodes-ok/rule-porter) from .cursor/rules/');
  lines.push('');

  // Global rules
  if (globalRules.length > 0) {
    lines.push('## Global Rules');
    lines.push('');

    for (var i = 0; i < globalRules.length; i++) {
      var rule = globalRules[i];
      var heading = rule.description || rule.name;
      lines.push('### ' + heading);
      lines.push('');
      if (rule.body) {
        lines.push(rule.body);
        lines.push('');
      }
    }
  }

  // Conditional rules
  if (conditionalRules.length > 0) {
    lines.push('## Conditional Rules');
    lines.push('');

    for (var j = 0; j < conditionalRules.length; j++) {
      var cRule = conditionalRules[j];
      var cHeading = cRule.description || cRule.name;

      lines.push('### ' + cHeading);
      lines.push('');

      if (cRule.globs) {
        var globStr = Array.isArray(cRule.globs) ? JSON.stringify(cRule.globs) : cRule.globs;
        lines.push('*Applies to: `' + globStr + '`*');
        lines.push('');
        warnings.push({
          rule: cRule.name,
          message: 'Glob pattern "' + globStr + '" converted to comment. AGENTS.md has no native file scoping.'
        });
      } else {
        warnings.push({
          rule: cRule.name,
          message: 'No glob pattern and not alwaysApply. This was a manual-attach rule in Cursor — review placement.'
        });
      }

      if (cRule.body) {
        lines.push(cRule.body);
        lines.push('');
      }
    }
  }

  return {
    content: lines.join('\n').trimEnd() + '\n',
    filename: 'AGENTS.md',
    warnings: warnings
  };
}

module.exports = { convert: convert };
