'use strict';

// Convert parsed Cursor rules to CLAUDE.md format
// CLAUDE.md is a single flat markdown file used by Claude Code.
// Structure:
//   # CLAUDE.md
//   Global rules first (no scoping mechanism)
//   Then conditional rules with file context as comments

function convert(rules) {
  var lines = [];
  var warnings = [];

  var globalRules = rules.filter(function(r) { return r.alwaysApply; });
  var conditionalRules = rules.filter(function(r) { return !r.alwaysApply; });

  lines.push('# CLAUDE.md');
  lines.push('');
  lines.push('> Generated by [rule-porter](https://github.com/nedcodes-ok/rule-porter) from .cursor/rules/');
  lines.push('');

  // Global rules — no section header needed, they're the default
  for (var i = 0; i < globalRules.length; i++) {
    var rule = globalRules[i];
    var heading = rule.description || rule.name;
    lines.push('## ' + heading);
    lines.push('');
    if (rule.body) {
      lines.push(rule.body);
      lines.push('');
    }
  }

  // Conditional rules
  if (conditionalRules.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## File-Specific Rules');
    lines.push('');
    lines.push('> Note: CLAUDE.md does not support file-pattern scoping. These rules were originally scoped to specific file types in Cursor.');
    lines.push('');

    for (var j = 0; j < conditionalRules.length; j++) {
      var cRule = conditionalRules[j];
      var cHeading = cRule.description || cRule.name;

      lines.push('### ' + cHeading);
      lines.push('');

      if (cRule.globs) {
        lines.push('*Originally scoped to: `' + cRule.globs + '`*');
        lines.push('');
        warnings.push({
          rule: cRule.name,
          message: 'Glob pattern "' + cRule.globs + '" noted as comment. CLAUDE.md has no file scoping.'
        });
      }

      if (cRule.body) {
        lines.push(cRule.body);
        lines.push('');
      }
    }
  }

  return {
    content: lines.join('\n').trimEnd() + '\n',
    filename: 'CLAUDE.md',
    warnings: warnings
  };
}

module.exports = { convert: convert };
