'use strict';

// Convert parsed Cursor rules to GitHub Copilot instructions format
// File: .github/copilot-instructions.md
// Copilot instructions is a single flat markdown file with no scoping mechanism.

function convert(rules) {
  var lines = [];
  var warnings = [];

  var globalRules = rules.filter(function(r) { return r.alwaysApply; });
  var conditionalRules = rules.filter(function(r) { return !r.alwaysApply; });

  lines.push('# Copilot Instructions');
  lines.push('');
  lines.push('> Generated by [rule-porter](https://github.com/nedcodes-ok/rule-porter) from .cursor/rules/');
  lines.push('');

  // All rules merged — Copilot has no scoping
  var allRules = globalRules.concat(conditionalRules);

  for (var i = 0; i < allRules.length; i++) {
    var rule = allRules[i];
    var heading = rule.description || rule.name;
    lines.push('## ' + heading);
    lines.push('');

    if (!rule.alwaysApply) {
      if (rule.globs) {
        lines.push('*Originally scoped to: `' + rule.globs + '`*');
        lines.push('');
        warnings.push({
          rule: rule.name,
          message: 'Glob pattern "' + rule.globs + '" lost. Copilot instructions have no file scoping.'
        });
      } else {
        warnings.push({
          rule: rule.name,
          message: 'No glob pattern and not alwaysApply. This was a manual-attach rule in Cursor — review placement.'
        });
      }
    }

    if (rule.body) {
      lines.push(rule.body);
      lines.push('');
    }
  }

  return {
    content: lines.join('\n').trimEnd() + '\n',
    filename: path.join('.github', 'copilot-instructions.md'),
    warnings: warnings
  };
}

var path = require('path');

module.exports = { convert: convert };
