'use strict';

var path = require('path');

// Convert parsed rules to Cursor .mdc format
// Each rule becomes a separate .mdc file in .cursor/rules/
// Returns multiple files instead of a single output

function slugify(str) {
  return str.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}

function convert(rules) {
  var files = [];
  var warnings = [];

  for (var i = 0; i < rules.length; i++) {
    var rule = rules[i];
    var lines = [];

    // Build frontmatter
    lines.push('---');
    if (rule.description) {
      lines.push('description: ' + rule.description);
    }
    if (rule.globs) {
      // Handle array globs properly (don't double-quote arrays)
      var globValue = rule.globs;
      if (Array.isArray(globValue)) {
        lines.push('globs: ' + JSON.stringify(globValue));
      } else if (typeof globValue === 'string' && globValue.match(/^\[.*\]$/)) {
        // Already stringified array - use as is (YAML-compatible)
        lines.push('globs: ' + globValue);
      } else {
        lines.push('globs: "' + globValue + '"');
      }
    }
    lines.push('alwaysApply: ' + (rule.alwaysApply ? 'true' : 'false'));
    lines.push('---');

    if (rule.body) {
      lines.push(rule.body);
    }

    var fileName = slugify(rule.name || rule.description || ('rule-' + (i + 1)));
    files.push({
      name: fileName + '.mdc',
      content: lines.join('\n') + '\n'
    });
  }

  // For multi-file output, content is a summary and files array is the real output
  var summaryLines = [];
  summaryLines.push('# Cursor Rules');
  summaryLines.push('');
  summaryLines.push('> Generated by [rule-porter](https://github.com/nedcodes-ok/rule-porter)');
  summaryLines.push('');
  summaryLines.push(files.length + ' rule file' + (files.length === 1 ? '' : 's') + ' in .cursor/rules/');
  summaryLines.push('');
  for (var j = 0; j < files.length; j++) {
    summaryLines.push('- ' + files[j].name);
  }

  return {
    content: summaryLines.join('\n') + '\n',
    filename: path.join('.cursor', 'rules', ''),
    files: files,
    multiFile: true,
    warnings: warnings
  };
}

module.exports = { convert: convert };
