'use strict';

// Convert parsed rules to Windsurf format (.windsurfrules)
// Single flat markdown file at project root, no scoping mechanism.

function convert(rules) {
  var lines = [];
  var warnings = [];

  var globalRules = rules.filter(function(r) { return r.alwaysApply; });
  var conditionalRules = rules.filter(function(r) { return !r.alwaysApply; });

  lines.push('# Windsurf Rules');
  lines.push('');
  lines.push('> Generated by [rule-porter](https://github.com/nedcodes-ok/rule-porter)');
  lines.push('');

  var allRules = globalRules.concat(conditionalRules);

  for (var i = 0; i < allRules.length; i++) {
    var rule = allRules[i];
    var heading = rule.description || rule.name;
    lines.push('## ' + heading);
    lines.push('');

    if (!rule.alwaysApply) {
      if (rule.globs) {
        lines.push('*Originally scoped to: `' + rule.globs + '`*');
        lines.push('');
        warnings.push({
          rule: rule.name,
          message: 'Glob pattern "' + rule.globs + '" lost. Windsurf rules have no file scoping.'
        });
      } else {
        warnings.push({
          rule: rule.name,
          message: 'No glob pattern and not alwaysApply. This was a manual-attach rule in Cursor — review placement.'
        });
      }
    }

    if (rule.body) {
      lines.push(rule.body);
      lines.push('');
    }
  }

  return {
    content: lines.join('\n').trimEnd() + '\n',
    filename: '.windsurfrules',
    warnings: warnings
  };
}

module.exports = { convert: convert };
